from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Item, ItemClassification

if TYPE_CHECKING:
    from .world import FuniRaccoonWorld

# Every item must have a unique integer ID associated with it.
ITEM_NAME_TO_ID = {
    "Moai": 1,
    "Street Lamp": 2,
    "Funbells": 3,
    "Lama/Alpaca Maybe?": 4,
    "Gym": 5,
    "Kei Truck": 6,
    "Vending Machine (accepts doubloons)": 7,
    "DOUBLOONS": 8,
    "Radio": 9,
    "unregistered firearm": 11,
    "Under Construction": 16,
    "Chicken": 17,
    "Washing Machine": 18,
    "Michelle": 19,
    "Brob Energy": 20,
    "Buisness Man": 21,
    "Concrete": 22,
    "Gizmo": 23,
    "Keksz": 24,
    "Michi": 25,
    "boingler": 26,
    "Paracetamol 650mg": 27,
    "Heavy Stone Torch": 28,
    "Computer Monitor (60hz)": 31,
    "Sign": 37,
    "Crack Head": 38,
    "Crayon": 39,
    "Cricket Bat": 40,
    "Pirate": 42,
    "Pirate 2": 43,
    "Pirate 3": 44,
    "UNDER CONSTRUCTION": 45,
    "Microwave": 48,
    "Toaster": 49,
    "Logan Left": 50,
    "Logan Right": 51,
    "Evil Fish": 52,
    "Feral Dog": 53,
    "Windmill": 54,
    "Marketable Plushie Box": 55,
    "Goo": 56,
    "Beenie the Birthday Boy": 57,
    "Fan": 59,
    "Letter B": 61,
    "Beenie, Our Savior": 62,
    "Candle": 63,
    "Funi Marketable Plushie": 64,
    "Patrick O'Hara": 65,
    "Toastie": 66,
    "Crisp": 67,
    "Flower": 68,
    "Divider": 69,
    "Office Chair": 70,
    "Desk": 71,
    "My Favourite Chair": 73,
    "Cricket": 74,
    "Crisps Undying Love": 75,
    "Blimbo Village Sign": 76,
    "Ougham Stone": 77,
    '"Cow"': 78,
    "Old Ass Rusty Ass Key": 80,
    "Plimbo": 81,
    "Fridge Key": 82,
    "Orphan Tyre": 84,
    "Papa Tyre": 85,
    "Smoker": 86,
    "Broken Truck": 87,
    "CHEESE": 88,
    "Gas Drum": 89,
    "Coffee Shop (closed)": 90,
    "Trolley": 91,
    "Folding Chair": 93,
    "Warning": 95,
    "Pickaxe": 96,
    "Broken Wall": 97,
    "Fone": 98,
    "Coffee Cup": 99,
    "Kettle": 100,
    "Radiator": 101,
    "Flower Blimbo": 102,
    "Bench": 104,
    "Evil Raccoon": 105,
    "Naked Fella": 106,
    "Bin": 107,
    "Knifedog": 109,
    "Suitcase": 110,
    "Cheeky Pint": 111,
    "Flowian": 112,
    "Bomb": 113,
    "Bell Boy": 114,
    "Demon Core": 115,
    "Apple": 116,
    "Gas Pumpo": 117,
    "CD Player": 118,
    "Radio Blimbo": 119,
    "Binocublo": 120,
    "Police Car": 121,
    "Hazelnut": 122,
    "Anti Sads": 123,
    '"TV Remote"': 124,
    "Synthesizer": 125,
    "Brick": 126,
    "Lloyd": 127,
    "Manhole Cover": 128,
    "Old Sign": 129,
    "Warning Sign": 130,
    "Area Sign": 131,
    "Orb": 132,
    "Ms. Heel": 134,
    "Mr. Heel": 135,
    "Belgium Waffle": 136,
    "GREENISH ABOMINATION": 137,
    "Priestess": 138,
    "Beenie Saves The Orphans": 140,
    "Eel Can": 141,
    "Barrel": 142,
    "BookBlo": 143,
    "Fridge": 144,
    "Fridgling": 145,
    "Snowball": 146,
    "Leeches!": 147,
    "Beach Ball": 150,
    "Milk Klubnika": 151,
    "Chairapist": 154,
    "Digital Polaroid Camera": 155,
    "Yolky": 156,
    "Pawn": 157,
    "Rook": 158,
    "Bishop": 159,
    "Queen": 160,
    "King": 161,
    "Real Gym": 162,
    "Spoonsweet": 163,
    "Wriks Celler": 164,
    "Door": 165,
    "Funi Raccoon Game Deluxe": 166,
    "Patrice": 167,
    "Goo Container": 168,
    "Butterfly": 169,
    "Patrick O Bobble": 170,
    "Dice": 171,
    "Lughling": 172,
    "Book Stack": 173,
    "Average Canadian": 174,
    "Cheese Wife": 175,
    "Kei Truck Radio": 201,
    "Kei Truck Toaster": 202,
    "10 Euro": 300,
    "100 Euro": 301,
}

# Items should have a defined default classification.
# In our case, we will make a dictionary from item name to classification.
DEFAULT_ITEM_CLASSIFICATIONS = {
    "Moai": ItemClassification.progression,
    "Street Lamp": ItemClassification.progression,
    "Funbells": ItemClassification.progression,
    "Lama/Alpaca Maybe?": ItemClassification.progression,
    "Gym": ItemClassification.progression,
    "Kei Truck": ItemClassification.progression,
    "Vending Machine (accepts doubloons)": ItemClassification.progression,
    "DOUBLOONS": ItemClassification.progression,
    "Radio": ItemClassification.progression,
    "Pirate": ItemClassification.progression,
    "unregistered firearm": ItemClassification.progression,
    "Under Construction": ItemClassification.progression,
    "Chicken": ItemClassification.progression,
    "Washing Machine": ItemClassification.progression,
    "Michelle": ItemClassification.progression,
    "Brob Energy": ItemClassification.progression,
    "Buisness Man": ItemClassification.progression,
    "Concrete": ItemClassification.progression,
    "Gizmo": ItemClassification.progression,
    "Keksz": ItemClassification.progression,
    "Michi": ItemClassification.progression,
    "boingler": ItemClassification.progression,
    "Paracetamol 650mg": ItemClassification.progression,
    "Heavy Stone Torch": ItemClassification.progression,
    "Computer Monitor (60hz)": ItemClassification.progression,
    "Sign": ItemClassification.progression,
    "Crack Head": ItemClassification.progression,
    "Crayon": ItemClassification.progression,
    "Cricket Bat": ItemClassification.progression,
    "UNDER CONSTRUCTION": ItemClassification.progression,
    "Microwave": ItemClassification.progression,
    "Toaster": ItemClassification.progression,
    "Logan Left": ItemClassification.progression,
    "Evil Fish": ItemClassification.progression,
    "Feral Dog": ItemClassification.progression,
    "Windmill": ItemClassification.progression,
    "Marketable Plushie Box": ItemClassification.progression,
    "Goo": ItemClassification.progression,
    "Beenie the Birthday Boy": ItemClassification.progression,
    "Fan": ItemClassification.progression,
    "Letter B": ItemClassification.progression,
    "Beenie, Our Savior": ItemClassification.progression,
    "Candle": ItemClassification.progression,
    "Funi Marketable Plushie": ItemClassification.progression,
    "Patrick O'Hara": ItemClassification.progression,
    "Toastie": ItemClassification.progression,
    "Crisp": ItemClassification.progression,
    "Flower": ItemClassification.progression,
    "Divider": ItemClassification.progression,
    "Office Chair": ItemClassification.progression,
    "Desk": ItemClassification.progression,
    "My Favourite Chair": ItemClassification.progression,
    "Cricket": ItemClassification.progression,
    "Crisps Undying Love": ItemClassification.progression,
    "Blimbo Village Sign": ItemClassification.progression,
    "Ougham Stone": ItemClassification.progression,
    '"Cow"': ItemClassification.progression,
    "Old Ass Rusty Ass Key": ItemClassification.progression,
    "Plimbo": ItemClassification.progression,
    "Fridge Key": ItemClassification.progression,
    "Orphan Tyre": ItemClassification.progression,
    "Papa Tyre": ItemClassification.progression,
    "Smoker": ItemClassification.progression,
    "Broken Truck": ItemClassification.progression,
    "CHEESE": ItemClassification.progression,
    "Gas Drum": ItemClassification.progression,
    "Coffee Shop (closed)": ItemClassification.progression,
    "Trolley": ItemClassification.progression,
    "Folding Chair": ItemClassification.progression,
    "Warning": ItemClassification.progression,
    "Pickaxe": ItemClassification.progression,
    "Broken Wall": ItemClassification.progression,
    "Fone": ItemClassification.progression,
    "Coffee Cup": ItemClassification.progression,
    "Kettle": ItemClassification.progression,
    "Radiator": ItemClassification.progression,
    "Flower Blimbo": ItemClassification.progression,
    "Bench": ItemClassification.progression,
    "Evil Raccoon": ItemClassification.progression,
    "Naked Fella": ItemClassification.progression,
    "Bin": ItemClassification.progression,
    "Knifedog": ItemClassification.progression,
    "Suitcase": ItemClassification.progression,
    "Cheeky Pint": ItemClassification.progression,
    "Flowian": ItemClassification.progression,
    "Bomb": ItemClassification.progression,
    "Bell Boy": ItemClassification.progression,
    "Demon Core": ItemClassification.progression,
    "Apple": ItemClassification.progression,
    "Gas Pumpo": ItemClassification.progression,
    "CD Player": ItemClassification.progression,
    "Radio Blimbo": ItemClassification.progression,
    "Binocublo": ItemClassification.progression,
    "Police Car": ItemClassification.progression,
    "Hazelnut": ItemClassification.progression,
    "Anti Sads": ItemClassification.progression,
    '"TV Remote"': ItemClassification.progression,
    "Synthesizer": ItemClassification.progression,
    "Brick": ItemClassification.progression,
    "Lloyd": ItemClassification.progression,
    "Manhole Cover": ItemClassification.progression,
    "Old Sign": ItemClassification.progression,
    "Warning Sign": ItemClassification.progression,
    "Area Sign": ItemClassification.progression,
    "Orb": ItemClassification.progression,
    "Ms. Heel": ItemClassification.progression,
    "Mr. Heel": ItemClassification.progression,
    "Belgium Waffle": ItemClassification.progression,
    "GREENISH ABOMINATION": ItemClassification.progression,
    "Priestess": ItemClassification.progression,
    "Beenie Saves The Orphans": ItemClassification.progression,
    "Eel Can": ItemClassification.progression,
    "Barrel": ItemClassification.progression,
    "BookBlo": ItemClassification.progression,
    "Fridge": ItemClassification.progression,
    "Fridgling": ItemClassification.progression,
    "Snowball": ItemClassification.progression,
    "Leeches!": ItemClassification.progression,
    "Beach Ball": ItemClassification.progression,
    "Milk Klubnika": ItemClassification.progression,
    "Chairapist": ItemClassification.progression,
    "Digital Polaroid Camera": ItemClassification.progression,
    "Yolky": ItemClassification.progression,
    "Pawn": ItemClassification.progression,
    "Rook": ItemClassification.progression,
    "Bishop": ItemClassification.progression,
    "Queen": ItemClassification.progression,
    "King": ItemClassification.progression,
    "Real Gym": ItemClassification.progression,
    "Spoonsweet": ItemClassification.progression,
    "Wriks Celler": ItemClassification.progression,
    "Door": ItemClassification.progression,
    "Funi Raccoon Game Deluxe": ItemClassification.progression,
    "Patrice": ItemClassification.progression,
    "Goo Container": ItemClassification.progression,
    "Butterfly": ItemClassification.progression,
    "Patrick O Bobble": ItemClassification.progression,
    "Dice": ItemClassification.progression,
    "Lughling": ItemClassification.progression,
    "Book Stack": ItemClassification.progression,
    "Average Canadian": ItemClassification.progression,
    "Cheese Wife": ItemClassification.progression,
    "Pirate 2": ItemClassification.progression,
    "Pirate 3": ItemClassification.progression,
    "Logan Right": ItemClassification.progression,
    "Kei Truck Radio": ItemClassification.progression,
    "Kei Truck Toaster": ItemClassification.progression,
    "100 Euro": ItemClassification.useful,
    "10 Euro": ItemClassification.filler
}


# Each Item instance must correctly report the "game" it belongs to.
# To make this simple, it is common practice to subclass the basic Item class and override the "game" field.
class FuniRaccoonItem(Item):
    game = "Funi Raccoon Game"


# Ontop of our regular itempool, our world must be able to create arbitrary amounts of filler as requested by core.
# To do this, it must define a function called world.get_filler_item_name(), which we will define in world.py later.
# For now, let's make a function that returns the name of a random filler item here in items.py.
def get_random_filler_item_name(world: FuniRaccoonWorld) -> str:
    return "100 Euro" if world.random.randint(0, 9) == 0 else "10 Euro"


def create_item_with_correct_classification(world: FuniRaccoonWorld, name: str) -> FuniRaccoonItem:
    classification = DEFAULT_ITEM_CLASSIFICATIONS[name]
    return FuniRaccoonItem(name, classification, ITEM_NAME_TO_ID[name], world.player)


def create_all_items(world: FuniRaccoonWorld) -> None:
    # Create one of every progression item.
    itempool: list[Item] = [
        world.create_item(name)
        for name, classification in DEFAULT_ITEM_CLASSIFICATIONS.items()
        if classification == ItemClassification.progression
    ]

    # Fill remaining location slots with filler (10 Euro / 100 Euro).
    number_of_unfilled_locations = len(world.multiworld.get_unfilled_locations(world.player))
    needed_filler = number_of_unfilled_locations - len(itempool)
    itempool += [world.create_filler() for _ in range(needed_filler)]

    world.multiworld.itempool += itempool
